version: '3.8'

services:
  app:
    # Imagen oficial en Docker Hub
    image: cfanton/cotizador-chile:latest
    container_name: cotizador_app
    restart: always
    ports:
      - "80:3000" # Exponemos en puerto 80 estándar para producción
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=cotizador_db
      - DB_DIALECT=mysql
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - db
    networks:
      - cotizador_net
    command: >
      sh -c "npm run init && npm run start"

  db:
    image: mysql:8.0
    container_name: cotizador_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cotizador_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cotizador_net
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:


networks:
  cotizador_net:
    driver: bridge
