version: '3.8'

services:
  app:
    # EN PRODUCCIÃ“N: Usamos la imagen que subiste (cargada con docker load)
    image: cotizador-app:latest
    container_name: cotizador_app
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=cotizador_db
      - DB_DIALECT=mysql
    env_file:
      - .env
    volumes:
      # Persistencia de uploads
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - db
    networks:
      - cotizador_net
    command: >
      sh -c "npm run init && npm run start"

  db:
    image: mysql:8.0
    container_name: cotizador_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cotizador_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cotizador_net
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:


networks:
  cotizador_net:
    driver: bridge
