version: '3.8'

services:
  app:
    # Descarga la imagen lista para usar desde la nube
    image: cfanton/cotizador-chile:latest
    container_name: cotizador_app_cliente
    restart: always
    ports:
      # La aplicación correrá en http://localhost:3001
      - "3001:3000"
    environment:
      - DB_HOST=db
      - DB_USER=cotizador_user
      - DB_PASS=cotizador_pass
      - DB_NAME=cotizador_db
      - DB_DIALECT=mysql
      - DB_PORT=3306
    env_file:
      - claves.env
    volumes:
      # Montamos solo subcarpetas específicas para no ocultar "templates" y "doc" de la imagen
      - ./archivos_subidos/temp:/app/uploads/temp
      - ./archivos_subidos/final:/app/uploads/final
    depends_on:
      - db
    command: >
      sh -c "npm run init && npm run start"

  db:
    image: mysql:8.0
    container_name: cotizador_db_cliente
    restart: always
    environment:
      # Usuario Root para emergencias
      MYSQL_ROOT_PASSWORD: root_super_secret
      # Usuario App (Coincide con init.sql y app env)
      MYSQL_DATABASE: cotizador_db
      MYSQL_USER: cotizador_user
      MYSQL_PASSWORD: cotizador_pass
    ports:
      # Puerto interno de base de datos (3307)
      - "3307:3306"
    volumes:
      - datos_mysql:/var/lib/mysql
      # Script de inicialización (Crea DB y Users)
      - ./mysql_init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  datos_mysql:
